---
include:
  #  - board: eyelash_corne_left
  #    shield: nice_view
  #    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: nice_view
    shield: eyelash_corne_right
    #snippet: zmk-usb-logging
  - board: nice_view
    shield: eyelash_corne_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_corne_studio_left
  - board: settings_reset
    shield: eyelash_corne_left
    #snippet: zmk-usb-logging
